export const sqlExpressions = [
  "Pick your neighborhood",
  "Neighborho = 'Downtown'",
  "Neighborho = 'East Downtown'",
  "Neighborho = 'Eastwood'",
  "Neighborho = 'First Ward'",
  "Neighborho = 'Heights'",
  "Neighborho = 'Hermann Park'",
  "Neighborho = 'Hyde Park'",
  "Neighborho = 'Medical Center'",
  "Neighborho = 'Memorial City'",
  "Neighborho = 'Memorial Park'",
  "Neighborho = 'Midtown'",
  "Neighborho = 'Montrose'",
  "Neighborho = 'Museum District'",
  "Neighborho = 'Northside Village'",
  "Neighborho = 'Rice Military'",
  "Neighborho = 'Rice University'",
  "Neighborho = 'Rice Village'",
  "Neighborho = 'Texas Southern University'",
  "Neighborho = 'Third Ward'",
  "Neighborho = 'UHD'",
  "Neighborho = 'University of Houston'",
  "Neighborho = 'Woodland Heights'",
];